services:
  - type: web
    name: wurdle
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: wurdle-disk
      mountPath: /opt/render/project/src/wordle.db
      sizeGB: 1
